// Thin root-scope service worker for tricho.app.
//
// Sole purpose: satisfy PWA install criteria on the apex (Chrome / Edge /
// Brave / Android require a registered SW + a manifest + HTTPS to surface
// the install prompt). This file MUST NOT cache anything — that is the
// job of /app/sw.js (scope /app/), generated by @vite-pwa/astro inside
// the app/ package. The marketing site at the apex relies on Cloudflare's
// edge cache + browser cache via the per-route Cache-Control headers in
// /_headers, NOT on a service-worker cache.
//
// See openspec/changes/marketing-site-and-pwa-split/specs/pwa-shell-routing
// (requirement: "Thin pass-through service worker registered at /sw.js
// scope /") for the canonical behaviour contract.

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('fetch', () => {
  // Pass-through: do NOT call event.respondWith. The browser handles every
  // request normally. Marketing pages at / and the PWA shell at /app/* both
  // work without any SW interception at this scope.
  return;
});
